<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */


class Error_Controller extends Template_Controller {

	// Disable this controller when Kohana is set to production mode.
	// See http://docs.kohanaphp.com/installation/deployment for more details.
	const ALLOW_PRODUCTION = FALSE;

	// Set the name of the template to use
	public $template = 'generic_login';
	public $my_them = '/my_theme';	


	public function index(){		
		$user_id = $this->input->cookie('id');
		$user_group_id = $this->input->cookie('group_id');
		//$user_group_id = cookie::get('user_group_id');
		
		if($user_id && $user_group_id && $user_group_id==1)
		{
			//header('Location: http://'. $_SERVER['SERVER_NAME'] . '/panel');			
			
		}
		else
		{
			header('Location: http://'. $_SERVER['SERVER_NAME'] . url::base());
			exit();
		}
		
		$login = $this->input->cookie('login');
		$arr_error = array('Таблица не найдена в вашем списке', 'Таблица не существует', 'Неизвестная ошибка', 'Строка не найдена' );

		$this->template->title = 'Ошибка';
		$this_error = $this->input->get('err');
		$this_error = intval($this_error);
		$this_error = isset($arr_error[$this_error]) ? $arr_error[$this_error] : $arr_error[1];
		$this->template->content = View::factory('error');
		$this->template->content->error = $this_error;
		$this->template->login = $login;
		
	}


		
	public function __call($method, $arguments)
	{
		
		header('Location: http://'. $_SERVER['SERVER_NAME'] . url::base() . 'error/?err=0');
		exit;
		// Disable auto-rendering
		$this->auto_render = FALSE;
		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => 'welcome/index/'.substr(Router::$current_uri, 8)));
	}
} // End Welcome Controller


