<?php
/*********************************************
*
*Путь указывается от корня сайта
*ВНИМАНИЕ!!! Для указания пути AJAX загрузки изображения перейдите в /media/editor/js/plugins/jbimages/config.php
*
*********************************************/
$my_config = array(
	'filepath' => ''
);

$tables = array(
	'r_mesta' => array(
		'title' => '',
		'order' => '',
		'visible' => '0',
		'fields' => array(
			'id' 	=> array(
				'type' 		=> 'int',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'region_id' 	=> array(
				'type' 		=> 'int',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'name' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'address' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'phones' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'phone_refs' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'worktime' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'site' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'tags' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'info' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'description' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'image' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'open' 	=> array(
				'type' 		=> 'int',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'riba' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'll' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'email' 	=> array(
				'type' 		=> 'string',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
		),
	),
	'slovar' => array(
		'title' => '',
		'order' => '',
		'visible' => '0',
		'fields' => array(
			'id' 	=> array(
				'type' 		=> 'int',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'name' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'description' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
		),
	),
	'slovar22' => array(
		'title' => '',
		'order' => '',
		'visible' => '0',
		'fields' => array(
			'id' 	=> array(
				'type' 		=> 'int',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'name' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
			'description' 	=> array(
				'type' 		=> 'text',
				'default' 		=> '',
				'title' 		=> '',
				'extras' 		=> '',
				'params' 		=> '',
				'class' 		=> '',
				'visible' 		=> '0',
				'enabled' 		=> '1',
			),
		),
	),
);